import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Ninja Block - Team",
  description: "Generated by create next app",
};

export default ({ children }: { children: React.ReactNode }) => {
  return children;
};
